services:
  web:
    build:
      context: ./web
    container_name: web
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - db
      
  tomcat:
    build:
      context: ./tomcat
    container_name: tomcat
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - db
  
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=appdb
    volumes:
      - db-storage:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
    networks:
      - my-network

volumes:
  db-storage:

networks:
  my-network:
    driver: bridge
